---
- hosts: server1
  name: Run Django Migrations
  vars:
    new_username: djangoadmin16
    dir_project: pyapps
    app_dir: ONTV_Files
    app_path: '/home/{{ new_username }}/{{ dir_project }}/{{ app_dir }}'
    pythonpath: '/home/{{ new_username }}/{{ dir_project }}/venv/bin/python3'
    virtualenv: '/home/{{ new_username }}/{{ dir_project }}/venv'
    item_email: tangpd@hotmail.com


  tasks:

# check if superuser user exists, if not, create user.
- name: Check if superuser user exists, if not, create user.
  django_manage:
    command: shell -c "from django.contrib.auth import get_user_model; MyUser = get_user_model(); MyUser.objects.filter( username__exact = '{{ django_superuser_username }}' ).count() == 0 or exit(); new_super_user = MyUser( username = '{{ django_superuser_username }}', password='{{ django_superuser_password }}', email='{{ django_superuser_email }}', is_superuser = True, is_staff = True ); new_super_user.save();"
    app_path: "{{ django_project_folder_path }}"
    virtualenv: "{{ django_virtualenv_path }}"


  - name: Django add superusers
    django_manage:
      app_path: '{{ app_path }}'
      virtualenv: '{{ virtualenv }}'
      command: "createsuperuser --noinput --username={{ item_email }} --email={{ item.mail }}" # Not idempotent, probably bug in django_manage module
    #with_items: "{{ seeder_admins }}"
    tags: django
    ignore_errors: yes
